project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

book:
  title: "Weapons and Wealth: Exploring Global Military Spending and the Arms Trade"
  author:
    - Shreyas Kamath (sk5677)
    - Shubham Pareek (p4553)
  repo-url: https://github.com/ShreyasK412/Weapons-and-Wealth
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


